name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set venv
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv sync --group lint
        uv sync
      
    - name: Install dependencies
      run: make
