name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python
      run: uv python install 3.13

    - name: Set venv
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv sync --group lint
      
    - name: Run make
      run: make lint
